### ISSUE TITLE
After any search command, gets stuck after first rescue (Tested with Player UI)

### ISSUE THREAD

**Issue by OKAllu** [olandra/CBSafe-Simulation#10]
After any kind of search command, the AI rescues the first victim they find and after that they get stuck either on the shore or they go towards the rest of the victims and get stuck in the water next to them.

**Comment by olandra** [comment]
Happens because the driver goes into AssistRescue state when the rescue is initialized and doesn't return to the SectorSearch state. The problem with this is that only the SectorSearch state responds to the AIInRescue status component, which is required.

I'll see how I can get the driver to return to the search state after the rescuable is safely out from the water.

**Comment by olandra** [comment]
Fixed in Changeset 288
