### ISSUE TITLE
Divers getting stuck

### ISSUE THREAD

**Issue by SeveriB** [olandra/CBSafe-Simulation#14]
-In shoreline searches diver gets stuck in the rocks if they don't find a victim underwater. the whole unit becomes unresponsive after this.
-In sector searches diver gets stuck if the capsule markers are too close to the rock or the boat.

Also if ordering a unit to do a search and firefighters are already wearing diving gear they will still go and put them on in the firetruck.

**Comment by olandra** [comment]
Shoreline issue:

FirefighterShorelinePhase1.cs ends to AITestingState when hitting the opposing river bank instead of handling AITaskDone.

This is a bad memory issue from the AI dev (me), but is also an issue with reality...This was left behind, but not confirmed by the professionals, for where to define the limit of this pattern in distance from the river bank the search was started from.

I'm assuming that it cannot be much more than 10 meters due to the resistance of water on the line they use to keep incrementing the distance for the pattern, so I'll fix it to either 10 or 15 meters before the AITaskDone is set to reset this chain.

---

The sector search has seen some random behavior and currently has no end condition that's reliable. This should, at least:

- Check for distance to the river bank / shoreline (the two areas we have on opposing banks at the moment)
- Sector search has limit for the iteration set -> Should set this one to max 3-5 and set AITaskDone

---

For the firefighters getting gears once more....

There are actually two conditions in the play here:

- The firefighter can have swimming gear on
- The firefighter can have diving gear on

The extra stop is for the diving gear, but it's currently blurred in the states with the swimming gear. At least the boat states only check for one condition: That the crew is ready for the task, not separating swimming gear from diving gear, so this issue is, in fact, reported backwards. The land unit diving gear check is there, but boat crew won't check for it. This is due to the visual limitations of our base system as there's no visual difference between firefighter having swimming gear for surface rescue task and diving gear on top of the swimming gear for search patterns which are all done **diving**.

**Comment by olandra** [comment]
Changeset 553 fixes the two search patterns from the shore. The SAR boat sector search still has some issue.

I'm not changing the getting diving gears unless we get visuals updated to tell a swimmer apart from a diver.
