### ISSUE TITLE
Rescuables walking in cirlces

### ISSUE THREAD

**Issue by SeveriB** [olandra/CBSafe-Simulation#15]
After getting rescued the rescuables will start walking in circles behind the ambulance

**Comment by olandra** [comment]
Glad someone reported this one...I's been one of my own tests to see if we actually have someone running tests for the AI as it's so obvious issue.

The problem here is that if two NPCs have the same exact destination and relatively same arrival time, neither of them reaches that exact position and will block it from each other. This is a minor fix with the comparison when the rescuable has reached their destination, including agent.stoppingDistance and  *hopefully* migrating to agent.hasPath over straight vector3.magnitude comparison.

**Comment by olandra** [comment]
Fixed in Changeset 551
