### ISSUE TITLE
23.9 Surface Rescue

### ISSUE THREAD

**Issue by JonniAV** [olandra/CBSafe-Simulation#50]
Problem: During surface rescue when rescuer takes victim to hold, the victim stands on the water(idle). This happens when victim is in distress or seems more specifically when victim is unconcious.

Notice: Also dead rescued is left on the shore wihtou anything being done. Happens when Unit 4055 executes search and finds a person underwater and drags this person back to shore.

**Comment by olandra** [comment]
The animation issue should be fixed in changeset 833.

Concerning the dead rescuable notice:
- Only related issues in one thread, please
- The dead cannot walk themselves and we have no ER crew on site. In addition there has been no information on how the deceased are handled in this kind of situations
